#!/bin/bash

CONFIGFILE="/usr/local/share/click_daemon.conf"
if [ -f ${CONFIGFILE}  ];
then
    source "${CONFIGFILE}"
fi

while true; do
    if [ -z "$(pidof ${SETUPMANETCMD})" ] 
    then
	echo "setting up manet"
	${SETUPMANETCMDLINE}
    fi

    sleep 1
done
